<?php

namespace App\Models;

use App\Traits\Syncable;
use App\Services\UniversalUserIdService;
use Database\Factories\UserFactory;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Relations\BelongsTo;
use Illuminate\Database\Eloquent\Relations\HasMany;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable, Syncable;

    protected $fillable = [
        'first_name',
        'last_name',
        'email',
        'password',
        'role_id',
        'phone',
        'address',
        'profile_photo',
        'credential_image_path',
        'is_active',
        'two_fa_code',
        'two_fa_expires_at',
        'two_fa_enabled',
    ];

    protected $hidden = [
        'password',
        'remember_token',
        'two_fa_code',
    ];

    protected static function booted(): void
    {
        static::creating(function (User $user) {
            if ($user->user_code !== null) {
                throw new \LogicException('User IDs are generated by the system and cannot be supplied manually.');
            }

            // Resolve the role slug so we can pick the right ID prefix
            $roleSlug = null;
            if ($user->role_id) {
                $role = \App\Models\Role::find($user->role_id);
                $roleSlug = $role?->slug;
            }

            $service = app(\App\Services\UniversalUserIdService::class);
            $prefix  = $service->prefixForRole($roleSlug);
            $user->user_code = $service->reserve($prefix);
        });

        static::created(function (User $user) {
            app(\App\Services\UniversalUserIdService::class)->assign($user);
        });

        static::updating(function (User $user) {
            if ($user->isDirty('user_code')) {
                throw new \LogicException('User IDs are permanent and cannot be changed.');
            }
        });
    }

    protected function casts(): array
    {
        return [
            'email_verified_at' => 'datetime',
            'password' => 'hashed',
            'is_active' => 'boolean',
        ];
    }

    public function role(): BelongsTo
    {
        return $this->belongsTo(Role::class);
    }

    public function hasRole(string $roleSlug): bool
    {
        return $this->role && $this->role->slug === $roleSlug;
    }

    public function hasAnyRole(array $roleSlugs): bool
    {
        return $this->role && in_array($this->role->slug, $roleSlugs);
    }

    public function hasPermission(string $permissionSlug): bool
    {
        return $this->role && $this->role->permissions()->where('slug', $permissionSlug)->exists();
    }
}
