/**
 * UserAccountPage — /users/account/student/:studentId
 *
 * After approving a student, admin:
 *  1. Reviews student info
 *  2. Auto-generates credentials (email + password)
 *  3. Creates the login account
 *  4. Delivers credentials via: Print · WhatsApp · SMS (tel:)
 */
import { useEffect, useState } from 'react';
import { useParams, Link } from 'react-router-dom';
import api from '../services/api';
import { authService } from '../services/authService';
import { useSettingsStore } from '../store/settingsStore';

// ── Types ─────────────────────────────────────────────────────────────────────
interface StudentRecord {
  id: number;
  student_id: string;
  first_name: string;
  last_name: string;
  gender: string;
  date_of_birth: string;
  nationality: string;
  county: string;
  address: string;
  grade_applying_for: string;
  father_name: string;
  mother_name: string;
  father_contact: string;
  mother_contact: string;
  application_status: string;
  class?: { id: number; name: string; section?: string };
  user?: { id: number; email: string; user_code: string; is_active: boolean; role?: { name: string } };
}

interface Role { id: number; name: string; slug: string; }

interface SavedCredentials {
  userCode: string;
  fullName: string;
  email: string;
  password: string;
  role: string;
  phone: string;
  studentId: string;
  schoolName: string;
  schoolPhone: string;
  schoolAddress: string;
}

// ── Helpers ───────────────────────────────────────────────────────────────────
function StrengthBar({ pw }: { pw: string }) {
  if (!pw) return null;
  let s = 0;
  if (pw.length >= 8)          s++;
  if (/[A-Z]/.test(pw))        s++;
  if (/[0-9]/.test(pw))        s++;
  if (/[^A-Za-z0-9]/.test(pw)) s++;
  const c = ['', 'bg-rose-400', 'bg-amber-400', 'bg-cyan-500', 'bg-emerald-500'];
  const l = ['', 'Weak', 'Fair', 'Good', 'Strong'];
  return (
    <div className="mt-1.5 space-y-0.5">
      <div className="flex gap-1">{[1,2,3,4].map(i => <div key={i} className={`h-1.5 flex-1 rounded-full ${i<=s?c[s]:'bg-slate-200'}`}/>)}</div>
      <p className="text-xs text-slate-400">Strength: <strong>{l[s]}</strong></p>
    </div>
  );
}

// ── Credential Card (print target) ────────────────────────────────────────────
function CredentialCard({ creds }: { creds: SavedCredentials }) {
  return (
    <div id="cred-print-card" style={{
      fontFamily: '"Times New Roman", serif', background: 'white',
      border: '2px solid #1e293b', borderRadius: 8, padding: '24px 28px',
      maxWidth: 420, width: '100%',
    }}>
      <div style={{ textAlign: 'center', borderBottom: '2px solid #e2e8f0', paddingBottom: 12, marginBottom: 16 }}>
        <h2 style={{ margin: 0, fontSize: 18, fontWeight: 900, textTransform: 'uppercase', letterSpacing: '0.05em' }}>
          {creds.schoolName}
        </h2>
        {creds.schoolAddress && <p style={{ margin: '4px 0 0', fontSize: 11, color: '#64748b' }}>{creds.schoolAddress}</p>}
        {creds.schoolPhone && <p style={{ margin: '2px 0 0', fontSize: 11, color: '#64748b' }}>Tel: {creds.schoolPhone}</p>}
        <h3 style={{ margin: '10px 0 0', fontSize: 13, fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.08em', color: '#0f172a' }}>
          Student Login Credentials
        </h3>
      </div>

      <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: 13 }}>
        {[
          ['Student Name', creds.fullName],
          ['Student ID',   creds.studentId],
          ['User ID',      creds.userCode],
          ['Role',         creds.role],
          ['Email / Username', creds.email],
          ['Password',     creds.password],
          ['Phone',        creds.phone || '—'],
        ].map(([label, value]) => (
          <tr key={label} style={{ borderBottom: '1px solid #e2e8f0' }}>
            <td style={{ padding: '7px 4px', fontWeight: 700, color: '#475569', width: '42%', whiteSpace: 'nowrap' }}>{label}:</td>
            <td style={{ padding: '7px 4px', fontWeight: label === 'Password' ? 900 : 600,
              fontFamily: label === 'Password' || label === 'User ID' ? 'monospace' : 'inherit',
              color: label === 'Password' ? '#0f172a' : '#1e293b',
              fontSize: label === 'Password' ? 15 : 13,
            }}>{value}</td>
          </tr>
        ))}
      </table>

      <div style={{ marginTop: 18, padding: '10px 12px', background: '#fef9c3', border: '1px solid #fde047', borderRadius: 6, fontSize: 11, color: '#854d0e' }}>
        ⚠️ Keep these credentials safe and confidential. Change your password after first login.
      </div>
      <p style={{ marginTop: 12, textAlign: 'center', fontSize: 10, color: '#94a3b8' }}>
        Generated by {creds.schoolName} · {new Date().toLocaleDateString()}
      </p>
    </div>
  );
}

// ── Credential delivery modal ─────────────────────────────────────────────────
function CredentialModal({
  creds, onClose,
}: {
  creds: SavedCredentials;
  onClose: () => void;
}) {
  const [whatsappNum, setWhatsappNum] = useState(
    // Strip non-digits and ensure country code; default to Liberia +231
    creds.phone.replace(/\D/g, '').replace(/^0/, '231') || ''
  );
  const [copied, setCopied] = useState(false);

  const credText =
    `🎓 ${creds.schoolName}\n` +
    `Student Login Credentials\n\n` +
    `👤 Name: ${creds.fullName}\n` +
    `🆔 Student ID: ${creds.studentId}\n` +
    `🔑 User ID: ${creds.userCode}\n` +
    `📧 Email: ${creds.email}\n` +
    `🔐 Password: ${creds.password}\n` +
    `🎭 Role: ${creds.role}\n\n` +
    `⚠️ Keep this safe. Change password after first login.\n` +
    `📞 Support: ${creds.schoolPhone || 'School office'}`;

  const handlePrint = () => {
    const printContents = document.getElementById('cred-print-card')?.outerHTML;
    if (!printContents) return;
    const w = window.open('', '_blank', 'width=600,height=700');
    if (!w) return;
    w.document.write(`<!DOCTYPE html><html><head>
      <title>Student Credentials</title>
      <style>
        body { margin: 20px; font-family: "Times New Roman", serif; background: white; }
        @page { size: A5; margin: 10mm; }
        @media print { body { margin: 0; } }
      </style>
    </head><body>${printContents}</body></html>`);
    w.document.close();
    setTimeout(() => { w.print(); w.close(); }, 400);
  };

  const handleWhatsApp = () => {
    const num = whatsappNum.replace(/\D/g, '');
    if (!num) return;
    const msg = encodeURIComponent(credText);
    window.open(`https://wa.me/${num}?text=${msg}`, '_blank');
  };

  const handleSMS = () => {
    const num = creds.phone.replace(/\s/g, '');
    const short =
      `${creds.schoolName} - Login\n` +
      `Email: ${creds.email}\n` +
      `Password: ${creds.password}\n` +
      `User ID: ${creds.userCode}`;
    window.open(`sms:${num}?body=${encodeURIComponent(short)}`, '_self');
  };

  const handleCopy = () => {
    navigator.clipboard.writeText(credText).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    });
  };

  return (
    <div className="fixed inset-0 z-50 flex items-start justify-center overflow-y-auto bg-black/70 p-4 pt-8">
      <div className="w-full max-w-xl space-y-4">
        {/* Modal header */}
        <div className="flex items-center justify-between rounded-xl border border-slate-200 bg-white px-5 py-4 shadow-sm">
          <div>
            <p className="text-xs font-bold uppercase tracking-widest text-emerald-700">Account created</p>
            <h2 className="text-lg font-bold text-slate-950">Deliver credentials</h2>
            <p className="text-xs text-slate-400 mt-0.5">
              Share login details with {creds.fullName} using one of the options below.
            </p>
          </div>
          <button onClick={onClose}
            className="flex h-8 w-8 items-center justify-center rounded-full text-slate-400 hover:bg-slate-100 text-xl">×</button>
        </div>

        {/* Credential card preview */}
        <div className="flex justify-center rounded-xl border border-slate-200 bg-slate-50 p-4">
          <CredentialCard creds={creds} />
        </div>

        {/* Action buttons */}
        <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm space-y-4">
          <p className="text-sm font-bold text-slate-950">Delivery options</p>

          {/* Print */}
          <button onClick={handlePrint}
            className="flex w-full items-center gap-4 rounded-xl border-2 border-slate-200 bg-white px-4 py-3.5 text-left transition-all hover:border-slate-950 hover:bg-slate-50">
            <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-slate-100 text-xl">🖨️</div>
            <div>
              <p className="text-sm font-bold text-slate-900">Print credential card</p>
              <p className="text-xs text-slate-400">Opens a print-ready A5 credential card in a new window</p>
            </div>
            <span className="ml-auto text-slate-300">›</span>
          </button>

          {/* WhatsApp */}
          <div className="rounded-xl border-2 border-slate-200 p-4 space-y-3">
            <div className="flex items-center gap-3">
              <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-emerald-100 text-xl">💬</div>
              <div>
                <p className="text-sm font-bold text-slate-900">Send via WhatsApp</p>
                <p className="text-xs text-slate-400">Opens WhatsApp with credentials pre-filled</p>
              </div>
            </div>
            <div className="flex gap-2">
              <div className="relative flex-1">
                <span className="absolute left-3 top-1/2 -translate-y-1/2 text-sm font-semibold text-slate-500">+</span>
                <input
                  type="tel"
                  value={whatsappNum}
                  onChange={(e) => setWhatsappNum(e.target.value.replace(/[^0-9]/g, ''))}
                  className="input-field pl-7 font-mono text-sm"
                  placeholder="2310770123456"
                />
              </div>
              <button onClick={handleWhatsApp} disabled={!whatsappNum}
                className="rounded-xl bg-emerald-600 px-4 py-2 text-sm font-bold text-white hover:bg-emerald-700 disabled:opacity-40 whitespace-nowrap">
                Open WhatsApp
              </button>
            </div>
            <p className="text-[10px] text-slate-400">
              Include country code, no + or spaces. Liberia: 231XXXXXXXXX
            </p>
          </div>

          {/* SMS */}
          <button onClick={handleSMS} disabled={!creds.phone}
            className="flex w-full items-center gap-4 rounded-xl border-2 border-slate-200 bg-white px-4 py-3.5 text-left transition-all hover:border-blue-400 hover:bg-blue-50 disabled:opacity-40 disabled:cursor-not-allowed">
            <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-blue-100 text-xl">📱</div>
            <div>
              <p className="text-sm font-bold text-slate-900">
                Send SMS to {creds.phone || 'no phone on file'}
              </p>
              <p className="text-xs text-slate-400">Opens your device SMS app with a short credential message</p>
            </div>
            <span className="ml-auto text-slate-300">›</span>
          </button>

          {/* Copy */}
          <button onClick={handleCopy}
            className={`flex w-full items-center gap-4 rounded-xl border-2 px-4 py-3.5 text-left transition-all ${
              copied ? 'border-emerald-400 bg-emerald-50' : 'border-slate-200 bg-white hover:border-slate-400 hover:bg-slate-50'
            }`}>
            <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-slate-100 text-xl">
              {copied ? '✅' : '📋'}
            </div>
            <div>
              <p className="text-sm font-bold text-slate-900">{copied ? 'Copied to clipboard!' : 'Copy credentials'}</p>
              <p className="text-xs text-slate-400">Copy formatted text to paste anywhere</p>
            </div>
            <span className="ml-auto text-slate-300">›</span>
          </button>
        </div>

        <div className="flex justify-end">
          <button onClick={onClose}
            className="rounded-lg bg-slate-950 px-5 py-2.5 text-sm font-semibold text-white hover:bg-cyan-700">
            Done
          </button>
        </div>
      </div>
    </div>
  );
}

// ── Main page ─────────────────────────────────────────────────────────────────
export default function UserAccountPage() {
  const { studentId } = useParams<{ studentId: string }>();
  const { settings }  = useSettingsStore();
  const { branding }  = settings;

  const [student, setStudent]     = useState<StudentRecord | null>(null);
  const [roles,   setRoles]       = useState<Role[]>([]);
  const [loading, setLoading]     = useState(true);
  const [saving,  setSaving]      = useState(false);
  const [error,   setError]       = useState('');

  // Credential delivery
  const [savedCreds, setSavedCreds] = useState<SavedCredentials | null>(null);

  // Form
  const [form, setForm] = useState({
    email:                '',
    password:             '',
    password_confirmation:'',
    role_id:              '',
    phone:                '',
    is_active:            true,
  });
  const [showPw,   setShowPw]   = useState(false);
  const [showConf, setShowConf] = useState(false);
  const [copied,   setCopied]   = useState(false);

  const pw = (chars: string) => chars[Math.floor(Math.random() * chars.length)];
  const genPw = (): string => {
    const U='ABCDEFGHJKLMNPQRSTUVWXYZ', L='abcdefghjkmnpqrstuvwxyz',
          D='23456789', S='!@#$%^&*', A=U+L+D+S;
    const p=[pw(U),pw(L),pw(D),pw(S),...Array.from({length:6},()=>pw(A))];
    for(let i=p.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[p[i],p[j]]=[p[j],p[i]];}
    return p.join('');
  };

  const refreshPassword = () => {
    const p = genPw();
    setForm((f) => ({ ...f, password: p, password_confirmation: p }));
    setCopied(false);
  };

  const copyPassword = () => {
    navigator.clipboard.writeText(form.password).then(() => {
      setCopied(true); setTimeout(() => setCopied(false), 2500);
    });
  };

  // Load
  useEffect(() => {
    if (!studentId) return;
    Promise.all([api.get(`/students/${studentId}`), authService.roles()])
      .then(([stuRes, rolesData]) => {
        const s: StudentRecord = stuRes.data;
        setStudent(s);
        setRoles(rolesData);
        const defRole = rolesData.find((r: Role) => r.slug === 'student');
        const auto = s.user ? '' : genPw();
        const phone = s.father_contact || s.mother_contact || '';
        setForm((f) => ({
          ...f,
          email:                s.user?.email || suggest(s),
          role_id:              s.user ? String((s.user as any).role_id || defRole?.id || '') : String(defRole?.id || ''),
          phone,
          is_active:            s.user?.is_active ?? true,
          password:             auto,
          password_confirmation: auto,
        }));
      })
      .catch(() => setError('Failed to load student record.'))
      .finally(() => setLoading(false));
  }, [studentId]);

  const suggest = (s: StudentRecord) =>
    `${s.first_name.toLowerCase().replace(/\s+/g,'.')}.${s.last_name.toLowerCase().replace(/\s+/g,'')}@sicss.edu`;

  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault(); setError('');
    if (!form.email.trim())   { setError('Email is required.'); return; }
    if (!form.role_id)        { setError('Please select a role.'); return; }
    const isNew = !student?.user;
    if (isNew) {
      if (!form.password || form.password.length < 8) { setError('Password must be at least 8 characters.'); return; }
      if (form.password !== form.password_confirmation) { setError('Passwords do not match.'); return; }
    }
    setSaving(true);
    try {
      let userCode = student?.user?.user_code || '';
      const roleName = roles.find((r) => String(r.id) === form.role_id)?.name || '';

      if (!isNew && student?.user?.id) {
        const res = await api.put(`/users/${student.user.id}`, {
          email:     form.email,
          role_id:   Number(form.role_id),
          phone:     form.phone || null,
          is_active: form.is_active,
          ...(form.password ? { password: form.password } : {}),
        });
        userCode = res.data?.user_code || userCode;
      } else {
        const res = await authService.createUser({
          first_name: student!.first_name,
          last_name:  student!.last_name,
          email:      form.email,
          password:   form.password,
          role_id:    Number(form.role_id),
          phone:      form.phone || undefined,
          address:    student!.address || undefined,
        });
        userCode = (res as any)?.user_code || '';
        const updated = await api.get(`/students/${studentId}`);
        setStudent(updated.data);
      }

      // Show credential delivery modal
      setSavedCreds({
        userCode,
        fullName:    `${student!.first_name} ${student!.last_name}`,
        email:       form.email,
        password:    form.password || '(unchanged)',
        role:        roleName,
        phone:       form.phone,
        studentId:   student!.student_id,
        schoolName:  branding.schoolName,
        schoolPhone: branding.schoolPhone,
        schoolAddress: branding.schoolAddress,
      });

      setForm((f) => ({ ...f, password: '', password_confirmation: '' }));
    } catch (err: any) {
      const errs = err.response?.data?.errors;
      setError(errs ? Object.values(errs).flat().join(' ') : err.response?.data?.message || 'Failed to save account.');
    } finally { setSaving(false); }
  };

  if (loading) return (
    <div className="flex items-center justify-center py-20">
      <div className="flex items-center gap-3 text-slate-500">
        <div className="h-5 w-5 animate-spin rounded-full border-2 border-slate-300 border-t-slate-700" />
        Loading student record…
      </div>
    </div>
  );

  if (!student) return (
    <div className="mx-auto max-w-lg rounded-xl border border-rose-200 bg-rose-50 p-8 text-center">
      <p className="text-rose-700 font-semibold">Student not found.</p>
      <Link to="/students" className="mt-4 inline-flex rounded-lg bg-slate-950 px-4 py-2 text-sm font-semibold text-white hover:bg-cyan-700">← Back</Link>
    </div>
  );

  const hasAccount = !!student.user;
  const appStatus  = student.application_status ?? 'pending';

  return (
    <div className="mx-auto max-w-3xl space-y-6">
      {/* Credential delivery modal */}
      {savedCreds && (
        <CredentialModal creds={savedCreds} onClose={() => setSavedCreds(null)} />
      )}

      {/* Back */}
      <div className="flex items-center gap-2">
        <Link to="/students" className="flex items-center gap-1.5 rounded-lg border border-slate-200 bg-white px-3 py-1.5 text-sm font-semibold text-slate-600 hover:bg-slate-50 shadow-sm">
          ← Return to students
        </Link>
        <span className="text-slate-300">/</span>
        <span className="text-sm text-slate-500">Configure account</span>
      </div>

      {/* Header */}
      <div>
        <p className="text-xs font-bold uppercase tracking-widest text-cyan-700">User account setup</p>
        <h1 className="mt-1 text-3xl font-bold tracking-tight text-slate-950">{student.first_name} {student.last_name}</h1>
        <div className="mt-2 flex flex-wrap items-center gap-2">
          <span className="font-mono text-sm font-semibold text-slate-500">{student.student_id}</span>
          <span className={`inline-flex rounded-full px-2.5 py-0.5 text-xs font-semibold ${appStatus==='approved'?'bg-emerald-100 text-emerald-800':appStatus==='pending'?'bg-amber-100 text-amber-800':'bg-rose-100 text-rose-700'}`}>
            {appStatus.charAt(0).toUpperCase()+appStatus.slice(1)}
          </span>
          {hasAccount && <span className="inline-flex items-center gap-1 rounded-full bg-blue-100 px-2.5 py-0.5 text-xs font-semibold text-blue-800">✓ Login exists — {student.user?.user_code}</span>}
        </div>
      </div>

      {/* Student info */}
      <div className="rounded-xl border border-slate-200 bg-white p-5 shadow-sm">
        <p className="mb-4 text-sm font-bold text-slate-900">Student information</p>
        <dl className="grid grid-cols-2 gap-3 sm:grid-cols-3 text-sm">
          {([
            ['Gender',         student.gender],
            ['Date of birth',  student.date_of_birth?.slice(0,10)],
            ['Nationality',    student.nationality],
            ['County',         student.county],
            ['Grade applying', student.grade_applying_for],
            ['Class assigned', student.class ? `${student.class.name}${student.class.section?` - ${student.class.section}`:''}` : '—'],
            ['Father',         student.father_name || '—'],
            ['Father contact', student.father_contact || '—'],
            ['Mother',         student.mother_name || '—'],
            ['Mother contact', student.mother_contact || '—'],
            ['Address',        student.address || '—'],
          ] as [string,string|undefined][]).map(([l,v]) => (
            <div key={l} className="rounded-lg bg-slate-50 px-3 py-2.5">
              <dt className="text-[10px] font-bold uppercase tracking-wide text-slate-400">{l}</dt>
              <dd className="mt-0.5 font-semibold text-slate-800 truncate capitalize">{v||'—'}</dd>
            </div>
          ))}
        </dl>
        <div className="mt-4 border-t border-slate-100 pt-4">
          <Link to={`/student-application?id=${studentId}`} className="text-xs font-semibold text-cyan-700 hover:underline">
            ✏️ Edit full application form →
          </Link>
        </div>
      </div>

      {/* Account form */}
      <form onSubmit={handleSave} className="rounded-xl border border-slate-200 bg-white p-6 shadow-sm space-y-5">
        <div className="flex items-center justify-between">
          <p className="text-sm font-bold text-slate-950">{hasAccount ? 'Update login account' : 'Create login account'}</p>
          {hasAccount && <span className="font-mono text-xs text-slate-400">{student.user?.user_code}</span>}
        </div>

        {error && (
          <div className="flex items-start gap-2 rounded-lg border border-rose-200 bg-rose-50 px-4 py-3 text-sm text-rose-700">
            <span className="mt-0.5 shrink-0">⚠</span>{error}
          </div>
        )}

        <div className="grid grid-cols-1 gap-4 sm:grid-cols-2">
          {/* Email */}
          <div className="sm:col-span-2">
            <label className="mb-1.5 block text-sm font-semibold text-slate-700">Email / Username <span className="text-rose-500">*</span></label>
            <input type="email" required value={form.email} onChange={(e)=>setForm({...form,email:e.target.value})} className="input-field" placeholder="student@sicss.edu" autoComplete="off" />
          </div>

          {/* Role */}
          <div>
            <label className="mb-1.5 block text-sm font-semibold text-slate-700">Role <span className="text-rose-500">*</span></label>
            <select required value={form.role_id} onChange={(e)=>setForm({...form,role_id:e.target.value})} className="input-field">
              <option value="">— Select role —</option>
              {roles.map((r)=><option key={r.id} value={r.id}>{r.name}</option>)}
            </select>
          </div>

          {/* Phone */}
          <div>
            <label className="mb-1.5 block text-sm font-semibold text-slate-700">Phone <span className="text-slate-400 font-normal text-xs">(for WhatsApp/SMS delivery)</span></label>
            <input value={form.phone} onChange={(e)=>setForm({...form,phone:e.target.value})} className="input-field" placeholder="e.g. 0770123456" />
          </div>

          {/* Password */}
          <div className="sm:col-span-2">
            <label className="mb-1.5 block text-sm font-semibold text-slate-700">
              {hasAccount ? 'New password' : 'Password'}{' '}
              {!hasAccount ? <span className="text-rose-500">*</span> : <span className="text-slate-400 font-normal text-xs">(leave blank to keep current)</span>}
            </label>

            {!hasAccount && (
              <div className="mb-2 flex flex-wrap items-center gap-2">
                <button type="button" onClick={refreshPassword} className="rounded-lg border border-cyan-300 bg-cyan-50 px-3 py-1 text-xs font-semibold text-cyan-800 hover:bg-cyan-100">
                  ↺ Regenerate
                </button>
                <button type="button" onClick={copyPassword} className={`rounded-lg border px-3 py-1 text-xs font-semibold transition-colors ${copied?'border-emerald-300 bg-emerald-50 text-emerald-800':'border-slate-300 bg-white text-slate-600 hover:bg-slate-50'}`}>
                  {copied ? '✓ Copied!' : '⎘ Copy password'}
                </button>
                <span className="text-xs text-slate-400">Auto-generated · hand to student securely</span>
              </div>
            )}

            <div className="relative">
              <input type={showPw?'text':'password'} required={!hasAccount} minLength={8}
                value={form.password} onChange={(e)=>setForm({...form,password:e.target.value,password_confirmation:e.target.value})}
                className="input-field pr-10 font-mono" placeholder="Min. 8 characters" autoComplete="new-password" />
              <button type="button" tabIndex={-1} onClick={()=>setShowPw(v=>!v)}
                className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400 hover:text-slate-600">
                {showPw?'🙈':'👁'}
              </button>
            </div>
            <StrengthBar pw={form.password} />
          </div>

          {/* Confirm — only for editing */}
          {hasAccount && (
            <div className="sm:col-span-2">
              <label className="mb-1.5 block text-sm font-semibold text-slate-700">Confirm new password</label>
              <div className="relative">
                <input type={showConf?'text':'password'} value={form.password_confirmation}
                  onChange={(e)=>setForm({...form,password_confirmation:e.target.value})}
                  className={`input-field pr-10 ${form.password_confirmation&&form.password!==form.password_confirmation?'border-rose-400 bg-rose-50':''}`}
                  placeholder="Re-enter new password" autoComplete="new-password" />
                <button type="button" tabIndex={-1} onClick={()=>setShowConf(v=>!v)}
                  className="absolute right-3 top-1/2 -translate-y-1/2 text-slate-400 hover:text-slate-600">
                  {showConf?'🙈':'👁'}
                </button>
              </div>
              {form.password_confirmation&&form.password!==form.password_confirmation&&<p className="mt-1 text-xs text-rose-600">Passwords do not match.</p>}
            </div>
          )}

          {/* Active */}
          <div className="flex items-center gap-3 pt-2">
            <label className="flex cursor-pointer items-center gap-2">
              <div onClick={()=>setForm(f=>({...f,is_active:!f.is_active}))}
                className={`relative h-6 w-11 rounded-full transition-colors ${form.is_active?'bg-emerald-500':'bg-slate-300'}`}>
                <span className={`absolute top-0.5 h-5 w-5 rounded-full bg-white shadow transition-transform ${form.is_active?'translate-x-5':'translate-x-0.5'}`}/>
              </div>
              <span className="text-sm font-medium text-slate-700">Account active</span>
            </label>
          </div>
        </div>

        <div className="flex flex-wrap items-center justify-between gap-3 border-t border-slate-100 pt-5">
          <Link to="/students" className="rounded-lg border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-600 hover:bg-slate-50">
            ← Return to students
          </Link>
          <button type="submit" disabled={saving}
            className="rounded-lg bg-slate-950 px-6 py-2.5 text-sm font-bold text-white hover:bg-cyan-700 disabled:opacity-50 transition-colors">
            {saving ? 'Saving…' : hasAccount ? '💾 Update account' : '✓ Create account'}
          </button>
        </div>
      </form>

      {/* Existing account info + re-deliver button */}
      {hasAccount && student.user && (
        <div className="rounded-xl border border-emerald-200 bg-emerald-50 p-5">
          <div className="flex items-center justify-between flex-wrap gap-3">
            <div>
              <p className="text-sm font-bold text-emerald-900">✓ Account is ready</p>
              <p className="mt-0.5 text-sm text-emerald-700">
                Login: <strong>{student.user.email}</strong> · User ID: <span className="font-mono font-semibold">{student.user.user_code}</span>
              </p>
            </div>
            <button
              onClick={() => setSavedCreds({
                userCode:     student.user!.user_code,
                fullName:     `${student.first_name} ${student.last_name}`,
                email:        student.user!.email,
                password:     '(saved — reset if needed)',
                role:         student.user?.role?.name || 'Student',
                phone:        form.phone,
                studentId:    student.student_id,
                schoolName:   branding.schoolName,
                schoolPhone:  branding.schoolPhone,
                schoolAddress:branding.schoolAddress,
              })}
              className="rounded-lg border border-emerald-300 bg-white px-4 py-2 text-sm font-semibold text-emerald-800 hover:bg-emerald-100">
              🖨️ Re-deliver credentials
            </button>
          </div>
        </div>
      )}
    </div>
  );
}
